### ISSUE TITLE
Change Title of the website

### ISSUE THREAD

**Issue by Gimhan-minion** [G2Labs/G2-Site#21]
**Is your feature request related to a problem? Please describe.**
Webpage title has to be updated

**Describe the solution you'd like**
Change to "G2 Labs Official Website"

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by abhi87374** [comment]
I would like to work on this, Plz assign this to me....

**Comment by sumit-022** [comment]
I can work on this. Please assign me this issue
